### ISSUE TITLE
Flinthook: deadlocks after intro or screen with disk logo

### ISSUE THREAD

**Issue by rfht** [rfht/fnaify#5]
Description:

* see title

log.txt:

* `Paris.Engine.WebServices.GetBinaryRequest : ERROR | GetBinaryRequest Error: NameResolutionFailure`

Possible Solution:

* [Contacted devs, maybe WebServices can be disabled and this might solve the problem](https://steamcommunity.com/app/401710/discussions/0/135514889557801381/?ctp=3#c1319961618837962338)

**Comment by thfrwn** [comment]
Maybe related to Paris Engine? (see Wizorb)

**Comment by thfrwn** [comment]
Flinthook is now running with `MONO_IOMAP=all` and the bundled mono dlls in the folder. Need to identify what's going on with the mono libraries. Seems to run well otherwise

**Comment by rfht** [comment]
that now doesn't work anymore. Game just says "Killed" and never launches. Similarity with RCRU is the use of NLog

**Comment by rfht** [comment]
NLog requires msbuild - maybe that's what's missing...

**Comment by rfht** [comment]
Now works after replacing NLog with latest version (4.6.5) and latest fnaify - but make sure to have `NLog.*.config` still in the repository!

**Comment by rfht** [comment]
fnaify now contains logic to detect outdated `NLog.dll` (https://thfr.info/cgi-bin/cvsweb/projects/fnaify/fnaify?rev=1.91&content-type=text/x-cvsweb-markup); otherwise runs fine on brief testing. Closing issue.
