### ISSUE TITLE
Games requiring steamwrapper.so

### ISSUE THREAD

**Issue by rfht** [rfht/fnaify#9]
This appears to be DRM-related

List:

* Gateways

**Comment by thfrwn** [comment]
The DRM-free version of Gateways from the developer webpage (via humblebundle) works fine, so closing this issue.

**Comment by rfht** [comment]
As of 2020-01-03, Dead Pixels now ships with steamwrapper.dll. It fails to run with an error box saying: `API_RunCallbacks`, which fgrep(1) shows to be in `steam_api.dll`, `Dead Pixels.exe`, and `steamwrapper.dll`.

**Comment by rfht** [comment]
appears to be resolved since adjustments to fnaify with libstubborn etc, as of 2020-06-20. Reopen if needed. Note the game now has issues with lack of MONO_IOMAP support.
